@ECHO OFF
set THIS=%~pd0
mkdir %THIS%..\build 2>nul
pushd %THIS%..\build

SET BOOST_ROOT=%1
SET ZLIB_ROOT=%2

IF "%BOOST_ROOT%"=="" (
    ECHO Usage %~nx0 $BOOST_ROOT $ZLIB_ROOT
    popd
    EXIT /B 1
)

IF "%ZLIB_ROOT%"==""  (
    ECHO Usage %~nx0 $BOOST_ROOT $ZLIB_ROOT
    popd
    EXIT /B 1
)

SET OPT=-DCBash_BUILD_SHARED_LIBS=ON
SET OPT=%OPT% -DBoost_NO_SYSTEM_PATHS=ON
SET OPT=%OPT% -DCBash_USE_STATIC_RUNTIME=OFF
SET OPT=%OPT% -DCBash_NO_BOOST_ZLIB=ON
SET OPT=%OPT% -DBOOST_ROOT=%BOOST_ROOT%
SET OPT=%OPT% -DBOOST_INCLUDEDIR=%BOOST_ROOT%
SET OPT=%OPT% -DBOOST_LIBRARYDIR=%BOOST_ROOT%\stage\lib
SET OPT=%OPT% -DZLIB_INCLUDE_DIR=%ZLIB_ROOT%
SET OPT=%OPT% -DZLIB_LIBRARY_RELEASE=%ZLIB_ROOT%\build\Release\zlibstatic.lib
SET OPT=%OPT% -DZLIB_LIBRARY_DEBUG=%ZLIB_ROOT%\build\Debug\zlibstaticd.lib

cmake .. %OPT%

:EXIT
popd

